version: '3'
services:
  jenkins:
    build:
      context: ./jenkins/
      dockerfile: Dockerfile
    image: product-review
    container_name: jenkins-ci
    command: sh -c "(/var/tmp/start-configure-jenkins.sh&) && /usr/local/bin/jenkins.sh"
    ports:
      - '8080:8080'
      - '50000:50000'
      
    

