pipeline {
    agent any
	environment {
	  NEXUS_HOST = 'nexus:8081'
	  SONAR_HOST = 'http://sonarqube:9000'
	  APP_VERSION = sh(returnStdout: true, script: """ echo \$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' product_service/pom.xml) """)
	}
    stages {
        stage('Build') {
            steps {
                dir('product_service'){
                    echo 'Clean/Build'
                    sh 'echo $APP_VERSION'
                    sh 'mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
                    echo 'Run sonar validation'
                    sh 'mvn sonar:sonar -Dsonar.scm.disabled=true -Dsonar.host.url=$SONAR_HOST'
                }
            }
        }
        stage('Test') {
            steps {
                dir('product_service'){
                    echo 'Testing'
                    sh 'mvn test'
                }
            }
        }
        stage('Publish') {
            steps {
                dir('product_service'){
                    sh 'mvn clean deploy -Ddocker.url=http://$NEXUS_HOST -Ddocker.user=$NEXUS_USER -Ddocker.password=$NEXUS_PASSWORD'
                }
            }
        }
    }    
    post {
        always {
            echo 'JENKINS PIPELINE'
        }
        success {
            echo 'JENKINS PIPELINE SUCCESSFUL'
            deleteDir()
        }
        failure {
            echo 'JENKINS PIPELINE FAILED'
            deleteDir()
        }
        unstable {
            echo 'JENKINS PIPELINE WAS MARKED AS UNSTABLE'
        }
        changed {
            echo 'JENKINS PIPELINE STATUS HAS CHANGED SINCE LAST EXECUTION'
        }
    }
}