pipeline {
    agent any
	environment {
	  NEXUS_HOST = '192.168.99.100:8081'
	  SONAR_HOST = 'http://192.168.99.100:9000'
	  NEXUS_USER = 'admin'
	  NEXUS_PASSWOD = 'gabriel12'
	  //DOCKER_VERSION = sh(returnStdout: true, script: """ echo \$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="properties"]/*[local-name()="docker-version"]/text()' pom.xml) """)
	  APP_VERSION = sh(returnStdout: true, script: """ echo \$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml) """)
	}
    stages {
        stage('Build') {
            steps {
                echo 'Clean/Build'
				sh 'echo $APP_VERSION'
                sh 'mvnw clean install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
                sh 'mvnw test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin'
				sh 'docker build . -t $NEXUS_HOST/spring-petclinic:$DOCKER_VERSION'
                sh 'docker push $DOCKERHUB_USER/spring-petclinic:$DOCKER_VERSION'
            }
        }
    }    
    post {
        always {
            echo 'JENKINS PIPELINE'
        }
        success {
            echo 'JENKINS PIPELINE SUCCESSFUL'
        }
        failure {
            echo 'JENKINS PIPELINE FAILED'
        }
        unstable {
            echo 'JENKINS PIPELINE WAS MARKED AS UNSTABLE'
        }
        changed {
            echo 'JENKINS PIPELINE STATUS HAS CHANGED SINCE LAST EXECUTION'
        }
    }
}