pipeline {
    agent any
	environment {
	  NEXUS_HOST = 'nexus:8081'
	  SONAR_HOST = 'http://sonarqube:9000'
      SONAR_TOKEN='1d9c085bcbae588bbb8cf89ee9d96e9ed9d4e443'
	  NEXUS_USER = 'admin'
	  NEXUS_PASSWOD = 'gabriel12'
	  APP_VERSION = sh(returnStdout: true, script: """ echo \$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' product_service/pom.xml) """)
	}
    stages {
        stage('Build') {
            steps {
                dir('product_service'){
                    echo 'Clean/Build'
                    sh 'echo $APP_VERSION'
                    sh 'mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
                    echo 'Run sonar validation'
                    sh 'mvn sonar:sonar -Dsonar.scm.disabled=true -Dsonar.host.url=$SONAR_HOST'
                }
            }
        }
        stage('Test') {
            steps {
                dir('product_service'){
                    echo 'Testing'
                    sh 'mvn test'
                }
            }
        }
        stage('Publish') {
            steps {
                sh 'echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin'
				sh 'docker build . -t $NEXUS_HOST/product-service:$DOCKER_VERSION'
                sh 'docker push $DOCKERHUB_USER/product-service:$DOCKER_VERSION'
            }
        }
    }    
    post {
        always {
            echo 'JENKINS PIPELINE'
        }
        success {
            echo 'JENKINS PIPELINE SUCCESSFUL'
            deleteDir()
        }
        failure {
            echo 'JENKINS PIPELINE FAILED'
            deleteDir()
        }
        unstable {
            echo 'JENKINS PIPELINE WAS MARKED AS UNSTABLE'
        }
        changed {
            echo 'JENKINS PIPELINE STATUS HAS CHANGED SINCE LAST EXECUTION'
        }
    }
}